import { Head, Link } from '@inertiajs/react';
import { ArrowLeft, Printer } from 'lucide-react';
import { useEffect } from 'react';
import { Button } from '@/components/ui/button';
import financialReports from '@/routes/financial-reports';

type MonthRow = {
    month: string;
    label: string;
    total: number;
    vouchers: number;
};

type DepartmentRow = {
    id: string;
    name: string;
    code: string;
    paidTotal: number;
    paidCount: number;
    pendingTotal: number;
    pendingCount: number;
};

type Props = {
    report: 'monthly' | 'department';
    year: number;
    total: number;
    months?: MonthRow[];
    departments?: DepartmentRow[];
    generatedAt: string;
    generatedBy: string;
};

const money = (value: number): string =>
    value === 0
        ? '—'
        : value.toLocaleString('en-GB', {
              minimumFractionDigits: 2,
              maximumFractionDigits: 2,
          });

export default function PrintReport({
    report,
    year,
    total,
    months = [],
    departments = [],
    generatedAt,
    generatedBy,
}: Props) {
    const title =
        report === 'monthly'
            ? `Expenditure by Month — ${year}`
            : `Expenditure by Department — ${year}`;

    // Open the print dialog once the page has rendered, which is what the
    // person clicking "Print report" was asking for.
    useEffect(() => {
        const timer = setTimeout(() => window.print(), 400);

        return () => clearTimeout(timer);
    }, []);

    const backHref =
        report === 'monthly'
            ? financialReports.monthly().url
            : financialReports.department().url;

    return (
        <div className="min-h-screen bg-white p-6 text-black md:p-10 print:p-0">
            <Head title={title} />

            {/* Screen-only controls; never appear on paper. */}
            <div className="mx-auto mb-6 flex max-w-3xl flex-wrap items-center justify-between gap-3 print:hidden">
                <Button variant="ghost" size="sm" asChild className="-ml-2">
                    <Link href={backHref} className="gap-2">
                        <ArrowLeft className="h-4 w-4" />
                        Back to report
                    </Link>
                </Button>
                <Button
                    size="sm"
                    className="gap-2"
                    onClick={() => window.print()}
                >
                    <Printer className="h-4 w-4" />
                    Print
                </Button>
            </div>

            <article className="mx-auto max-w-3xl">
                <header className="border-b-2 border-black pb-4">
                    <p className="text-xs tracking-widest uppercase">
                        Adentan Municipal Education Office
                    </p>
                    <h1 className="mt-1 text-2xl font-bold">{title}</h1>
                    <p className="mt-2 text-sm">
                        Generated by {generatedBy} on {generatedAt}
                    </p>
                </header>

                <table className="mt-6 w-full border-collapse text-sm">
                    <thead>
                        <tr className="border-b border-black text-left">
                            {report === 'monthly' ? (
                                <>
                                    <th className="py-2 pr-4 font-semibold">
                                        Month
                                    </th>
                                    <th className="py-2 pr-4 text-right font-semibold">
                                        Vouchers
                                    </th>
                                    <th className="py-2 text-right font-semibold">
                                        Total paid (GHS)
                                    </th>
                                </>
                            ) : (
                                <>
                                    <th className="py-2 pr-4 font-semibold">
                                        Code
                                    </th>
                                    <th className="py-2 pr-4 font-semibold">
                                        Department
                                    </th>
                                    <th className="py-2 pr-4 text-right font-semibold">
                                        Vouchers
                                    </th>
                                    <th className="py-2 text-right font-semibold">
                                        Total paid (GHS)
                                    </th>
                                </>
                            )}
                        </tr>
                    </thead>
                    <tbody>
                        {report === 'monthly'
                            ? months.map((row) => (
                                  <tr
                                      key={row.month}
                                      className="border-b border-neutral-300"
                                  >
                                      <td className="py-1.5 pr-4">
                                          {row.label}
                                      </td>
                                      <td className="py-1.5 pr-4 text-right tabular-nums">
                                          {row.vouchers || '—'}
                                      </td>
                                      <td className="py-1.5 text-right tabular-nums">
                                          {money(row.total)}
                                      </td>
                                  </tr>
                              ))
                            : departments.map((row) => (
                                  <tr
                                      key={row.id}
                                      className="border-b border-neutral-300"
                                  >
                                      <td className="py-1.5 pr-4 font-mono">
                                          {row.code}
                                      </td>
                                      <td className="py-1.5 pr-4">
                                          {row.name}
                                      </td>
                                      <td className="py-1.5 pr-4 text-right tabular-nums">
                                          {row.paidCount || '—'}
                                      </td>
                                      <td className="py-1.5 text-right tabular-nums">
                                          {money(row.paidTotal)}
                                      </td>
                                  </tr>
                              ))}
                    </tbody>
                    <tfoot>
                        <tr className="border-t-2 border-black font-semibold">
                            <td
                                className="py-2 pr-4"
                                colSpan={report === 'monthly' ? 2 : 3}
                            >
                                Total
                            </td>
                            <td className="py-2 text-right tabular-nums">
                                {money(total)}
                            </td>
                        </tr>
                    </tfoot>
                </table>

                <footer className="mt-8 border-t border-neutral-300 pt-3 text-xs">
                    <p>
                        Figures cover vouchers marked paid. This report was
                        generated from GovPay Desk and the act of generating it
                        is recorded in the system audit log.
                    </p>
                </footer>
            </article>
        </div>
    );
}
